### ISSUE TITLE
non-CUDA usage? (serial, multi-threded)

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#1]
Thrust offers serial and multi-threaded execution. Are there plans to support it also with ThrustRTC? Thanks

**Comment by fynv** [comment]
Sorry, there's no such plan. 
The aim of ThrustRTC is relatively simple comparing to Thrust. 
It just solves the type of tasks where you launch the computation from host side and get it executed on device side. So there's bunch of Thrust features missing, such as launch from host, execute on host, or launch from device and execute on device.

**Comment by fynv** [comment]
Also, currently it is not even thread-safe (for host).

**Comment by slayoo** [comment]
Thanks
(and to clarify, my point was about launching the computation from host and executing on device, just with the device being serial-CPU or multi-threaded-CPU, like OpenMP backend with Thrust)
