### ISSUE TITLE
report wrong number of argument for launch_n as exception

### ISSUE THREAD

**Issue by piotrbartman** [fynv/ThrustRTC#10]
It would be of great help if such things:

https://github.com/fynv/ThrustRTC/blob/6b40fc0481b82b3dee4247c894bc59d3e872d594/python/api_Context.cpp#L88

were reported as exceptions.
Thanks

**Comment by fynv** [comment]
I'm not quite familiar with python Exceptions. There are quite many of them: https://docs.python.org/3/library/exceptions.html. Not  sure which one I should throw in case of this. Is it ValueError? Or should I define another exception subclass and use it all through the project?

**Comment by piotrbartman** [comment]
I think `ValueError` is the best one in this situation.

**Comment by fynv** [comment]
I did quite a lot of changes in the python binding, trying to reflect every dectect error as a python Exception. The lasted pypi wheel (0.3.10) contains the fixes. Not tested very thoroughly. Please continue to file issues if there's anything wrong.
