### ISSUE TITLE
Give more useful debug feedback for internal error

### ISSUE THREAD

**Issue by edejong-caltech** [fynv/ThrustRTC#12]
It would be helpful if the error message `an internal error happend` reported in `check_i` in `ThrustRTC/Native.py` could provide more useful debug feedback. 

For instance, is it an error with argument length/type? Is there an illegal operation in the kernel? Is there a typecast error in the kernel?

**Comment by slayoo** [comment]
One example which can turn very puzzling: if the loop range parameter for `launch_n` is set to zero (what would intuitively result in no operation being performed), an "Internal error happened" `SystemError` is raised without any diagnostic message.

**Comment by fynv** [comment]
Will take a look at this soon.

**Comment by fynv** [comment]
I've just checked it version 0.3.11. Now the error message should look like:
cuLaunchKernel() failed with Error code: 1
Error Name: CUDA_ERROR_INVALID_VALUE
Error Description: invalid argument
Traceback (most recent call last):
  File "test_trtc.py", line 30, in <module>
    kernel.launch(0,0, [darr2, darr_out, trtc.DVInt32(5)])
  File "D:\workspace\ThrustRTC_local\install\test_python\ThrustRTC\Context.py", line 56, in launch
    return check_i(native.n_kernel_launch(
  File "D:\workspace\ThrustRTC_local\install\test_python\ThrustRTC\Native.py", line 16, in check_i
    raise SystemError("An internal error happend")
SystemError: An internal error happend

**Comment by slayoo** [comment]
Thank you!

**Comment by edejong-caltech** [comment]
Looks great, thank you!

**Comment by slayoo** [comment]
I guess this can be closed than
