### ISSUE TITLE
update conda package

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#13]
Would be great to update the conda packages available at fyplus channel here:
https://anaconda.org/fyplus/thrustrtc
(currently v0.2.0 is available only)
Thanks

**Comment by fynv** [comment]
The conda package were experimental. I've just uploaded 2 new packages built from the latest code. Please try if they help.

**Comment by slayoo** [comment]
Thank you!

**Comment by slayoo** [comment]
Let us also kindly ask if providing a CURandRTC package on conda would be feasible, thanks

**Comment by fynv** [comment]
Yes, just did it:
https://anaconda.org/fyplus/curandrtc

**Comment by slayoo** [comment]
Thank you!
