### ISSUE TITLE
Large alloc bug, regression in 0.3.11

### ISSUE THREAD

**Issue by piotrbartman** [fynv/ThrustRTC#15]
Here [Google Colab Reproduce Example](https://colab.research.google.com/drive/1IvE1J02ATWZsFNYim0q2G6aSrdEa8-bu?usp=sharing) CURandRTC latest + ThrustRTC 0.3.11 causes the kernel restart with the following message:

Jun 21, 2021, 4:16:23 PM | WARNING | terminate called after throwing an instance of 'std::bad_alloc'
-- | -- | --
Jun 21, 2021, 4:16:23 PM | WARNING | tcmalloc: **large alloc** 140212504444928 bytes == (nil) @ 0x7f85f414b887 0x7f85f2a41c29 0x7f85f2a42afb 0x7f85f2a42bb4 0x7f85f2a42c97 0x7f85cc3291fc 0x7f85cc33a86e 0x7f85cc326bec 0x7f85cc32818a 0x7f85cc34b621 0x7f85cc5f1dec 0x7f85cc5f0f55 0x7f85cc813df6 0x557f06d9e462 0x557f06e11fd5 0x557f06d9f30a 0x557f06e0d60e 0x557f06e0c4ae 0x557f06e0c1b3 0x557f06e0a660 0x557f06d9db59 0x557f06d9da50 0x557f06e11453 0x557f06e0c4ae 0x557f06d9f3ea 0x557f06e0d60e 0x557f06e0c4ae 0x557f06d9f3ea 0x557f06e0e32a 0x557f06e0c7ad 0x557f06d9fc9f

With ThrustRTC 0.3.10 it works.
I wonder if it is related to #14

**Comment by fynv** [comment]
My guess is that it was because I used Manylinux2010 docker image for a more compatible ABI, in order to help with #11...

**Comment by fynv** [comment]
Per request in #13, I've just made some conda packages. 
https://anaconda.org/fyplus/thrustrtc
Please see if they also help for this issue. If not I'll rebuild the pypi package.

**Comment by fynv** [comment]
Checked in version 0.3.12, the same as the conda package.
(Use 0.3.11 for CentOS only)

**Comment by piotrbartman** [comment]
Perfectly! Thanks!
