### ISSUE TITLE
a case of lack of type specifiers in header_of_structs.h

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#21]
@fynv, we are experiencing some weird regression (no idea if related to ThrustRTC or client code) and the symptoms are that previously working code started to fail to compile with errors pointing to lack of type specifiers in the header_of_structs.h, e.g.
```c++
     struct _S_d094442c7e83bcae
     {
         typedef _S_d094442c7e83bcae CurType;
          view_vec_in;
          view_vec_out;
         template<class _T0>
         __device__ inline auto operator()(const _T0& idx)
         {
         view_vec_out[idx]=(decltype(view_vec_out)::value_t)view_vec_in[idx];
         }
     };
```

(note that view_vec_in and view_vec_out have no types).

I'll be working on a minimal reproducer, meanwhile thought I'd post here to check if this doesn't perhaps ring a bell ...
Thanks

**Comment by fynv** [comment]
Just a guess, it could be a fail of one of:
cuMemAlloc()
cuMemcpyHtoD()
cuMemsetD8()
These could be called before m_name_view_cls  is set.

`DVVector::DVVector(const char* elem_cls, size_t size, void* hdata)
	: DVVectorLike(elem_cls, (std::string(elem_cls)+"&").c_str(), size)
{
	TRTC_Try_Init();
	
	CUdeviceptr dptr;
	if (!CheckCUresult(cuMemAlloc(&dptr, m_elem_size*m_size), "cuMemAlloc()")) return;
	m_data = (void*)dptr;
	if (hdata)
	{
		if (!CheckCUresult(cuMemcpyHtoD(dptr, hdata, m_elem_size*m_size), "cuMemcpyHtoD()")) return;
	}
	else
	{
		if (!CheckCUresult(cuMemsetD8(dptr, 0, m_elem_size*m_size), "cuMemsetD8()")) return;
	}

	m_name_view_cls = std::string("VectorView<") + m_elem_cls + ">";
}
`
If this is the case, there should be some related error message in stdout, before the code dump.

**Comment by slayoo** [comment]
Thanks! Exactly!
This is what is shown above the error message:
```
cuMemAlloc() failed with Error code: 700
Error Name: CUDA_ERROR_ILLEGAL_ADDRESS
Error Description: an illegal memory access was encountered
```
What could be the reason???

**Comment by fynv** [comment]
It is quite unlikely that cuMemAlloc() throws a CUDA_ERROR_ILLEGAL_ADDRESS.
But the following link reminded me that this could be "the result of a previous kernel call":
https://forums.developer.nvidia.com/t/cumemalloc-throw-cuda-error-illegal-address/59068

So maybe you should check the previous kernel call, is it a built-in kernel or a custom kernel? 
Then we check for things like an out-of-bound access.

**Comment by slayoo** [comment]
Thank you!
It's tricky. It is a set of tests which individually work OK, however when run in a sequence using pytest, some fail. Moreover, the error messages differ from run to run... will continue investigating. Thank you for your help!

**Comment by fynv** [comment]
I've just released a 0.3.16 patch, adding a new switch ThrustRTC.Set_Kernel_Debug(), which could be helpful to this case.
When it is set True,  cuCtxSynchronize() will be called after each kernel launch. 
If an error is returned, the CUDA code of the kernel will be dumped and the program will be terminated.

**Comment by slayoo** [comment]
Thank you, @fynv! 
I'll test it tomorrow

**Comment by slayoo** [comment]
@fynv trying out with 0.3.16 and with Set_Kernel_Debug(True) called changes indeed the behavior - a "Failed to build kernel" message is printed and test execution stops here. This is a progress. Yet, the dumped code is the same as was dumped previously - still need to debug more to understand where the  CUDA_ERROR_ILLEGAL_ADDRESS comes from here. Will write back. Thanks!

**Comment by slayoo** [comment]
getting close (something related with passing size=0), will fix tomorrow
Thanks again for support!

**Comment by slayoo** [comment]
well, fixed. the cause was passing 0 as second arg to device_vector()
Again, thanks
