### ISSUE TITLE
API addition to expose sync/wait functionality

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#3]
Currently when profiling code that uses ThrustRTC, execution times are in a potentially misleading way associated with subsequent API calls - apparently due to asyncronous execution. Would it be possible to expose some wait/sync feature in the ThrustRTC API so that one could enforce completion of execution of launched kernels?

**Comment by slayoo** [comment]
or perhaps two versions:
- launch()
- launch_and_wait()

or 

- launch(wait=False)
- launch(wait=True)

**Comment by slayoo** [comment]
ping? :)

**Comment by fynv** [comment]
Hey, sorry. Wasn't on this these days. Will take a look.
I didn't consider this as an issue, because all device->host transfers are now using the synchronized copy APIs. However, yes, profiling is a good point.

**Comment by slayoo** [comment]
thanks!

**Comment by fynv** [comment]
Added Wait() just now. (eb94b451a0284f1f277682995060dba104170339)

**Comment by slayoo** [comment]
kudos! Will try soon

**Comment by slayoo** [comment]
It does work! Thank you!
