### ISSUE TITLE
how to cite ThrustRTC? :)

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#4]

**Comment by fynv** [comment]
Just the URL: https://github.com/fynv/thrustrtc is fine.

**Comment by slayoo** [comment]
OK :)

**Comment by slayoo** [comment]
And here is the citation: https://www.ap.uj.edu.pl/diplomas/attachments/file/download/125485/
(@piotrbartman's MSc thesis)
Thank you!

**Comment by slayoo** [comment]
and one more: https://arxiv.org/abs/2101.06318
teaser plot:
![image](https://user-images.githubusercontent.com/89685/106070123-27c64200-6104-11eb-973d-3e3da4c03432.png)
(this is still a draft)
