### ISSUE TITLE
pip install ThrustRTC in Python 3.8

### ISSUE THREAD

**Issue by piotrbartman** [fynv/ThrustRTC#5]
Installing ThrustRTC by pip works only with Python 3.7, but with Python 3.8 I have:
```
ERROR: Could not find a version that satisfies the requirement ThrustRTC (from versions: none)
ERROR: No matching distribution found for ThrustRTC
```

**Comment by fynv** [comment]
I'm considering to transit to cffi to solve the Python versioning issue for good.. For now, please just try rebuilding locally. Sorry for the inconvenience.

**Comment by fynv** [comment]
Hi, I rewrote the Python wrapping layer with CFFI, and I've just uploaded a ThrustRTC-0.3.0-py3-none-any.whl package to PyPI. I intend to make it compatible to all Python 3.x as long as your ABI is compatible (Win64 or Linux64).
You can have a try now by "pip install ThrustRTC"
I will update the repository once I'm sure everything is still consistent after such a big change.

**Comment by piotrbartman** [comment]
It works! Thank you!
