### ISSUE TITLE
failing with exception in case CUDA not available

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#7]
Currently, even a ThrustRTC hello-world like
```python
import ThrustRTC
a = ThrustRTC.device_vector_from_list([1, 2, 3, 1, 2], 'int32_t')
```
when run on a machine without CUDA, fails ungently halting python:
```
libcuda.so not found
Cannot find CUDA driver. Exiting.
```
It would be great to raise an exception so that a user can catch it.

Perhaps it would even be better to report it by the import statement so one can ```try: import ThrustRTC``` (same for CURandRTC)

Thanks

**Comment by slayoo** [comment]
The current behavior is even more troublesome for Jupyter users:
![image](https://user-images.githubusercontent.com/89685/83321982-6691b880-a254-11ea-82c7-dae2a63ae8a4.png)

**Comment by fynv** [comment]
Yes, it is true I over-simplified the error handling. Thanks for pointing this out.
I've just updated ThrustRTC/CURandRTC to 0.3.5/0.1.5. 
Please check and see if the current behavior is what you are expecting.

**Comment by piotrbartman** [comment]
I had the same problem and ThrustRTC 0.3.5 fixed it.

**Comment by slayoo** [comment]
Perfect. Thank you!
