### ISSUE TITLE
segfault in reduction (due to NULL returned from native.n_reduce())

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#9]
in ``api_Reductions.cpp``, the native.n_reduce may return a nullptr:
https://github.com/fynv/ThrustRTC/blob/6b40fc0481b82b3dee4247c894bc59d3e872d594/python/api_Reductions.cpp#L56
but it is not handled in Reductions.py:
https://github.com/fynv/ThrustRTC/blob/bd26f89f380f33fe5122c97657b520b703fd74d3/python/ThrustRTC/Reductions.py#L18
and a segfault is triggered within ``ValueFromDVPtr``

HTH

**Comment by fynv** [comment]
Just did a fix in Reductions.py

**Comment by slayoo** [comment]
Thank you!
